name: lipforensics
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - contourpy=1.1.1
  - cycler=0.12.1
  - fonttools=4.53.1
  - freetype=2.14.1
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - kiwisolver=1.4.5
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libopenblas=0.3.30
  - libpng=1.6.51
  - libsqlite=3.51.1
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=1.24.4
  - openjpeg=2.5.3
  - openssl=3.6.0
  - packaging=25.0
  - pillow=10.4.0
  - pip=24.2
  - pthread-stubs=0.4
  - pyparsing=3.1.4
  - python=3.8.20
  - python_abi=3.8
  - readline=8.3
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tornado=6.4.1
  - unicodedata2=15.1.0
  - wheel=0.44.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - certifi==2021.5.30
      - face-alignment==1.4.2
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - joblib==1.0.1
      - lazy-loader==0.4
      - llvmlite==0.41.1
      - networkx==3.1
      - numba==0.58.1
      - opencv-python==4.12.0.88
      - pandas==1.3.1
      - python-dateutil==2.8.2
      - pytz==2021.1
      - pywavelets==1.4.1
      - scikit-image==0.21.0
      - scikit-learn==1.1.3
      - scipy==1.10.1
      - threadpoolctl==2.2.0
      - tifffile==2023.7.10
      - torch==1.9.0
      - torchvision==0.10.0
      - tqdm==4.62.0
      - typing-extensions==3.10.0.0
